#!/usr/bin/env python3

"""
Pairwise test generator for cppcheck using allpairspy.

- Generates pairwise combinations for:
    * --enable
    * --std
    * --platform
    * --inconclusive (on/off)
- Runs cppcheck against the unpacked e15/ directory
- Logs each run to ./logs/testcase_XX.log
"""

from allpairspy import AllPairs
from pathlib import Path
import subprocess
import shlex

# ==== CONFIGURATION ====

# 1) cppcheck --enable options
ENABLE_OPTS = [
    "warning",
    "style",
    "performance",
    "portability",
    "all",
]

# 2) cppcheck --std options (pick a small useful subset)
STD_OPTS = [
    "c++11",
    "c++14",
    "c++17",
]

# 3) cppcheck --platform options
PLATFORM_OPTS = [
    "unix32",
    "unix64",
    "win64",
]

# 4) whether to include --inconclusive
INCONCLUSIVE_OPTS = [
    False,
    True,
]

PARAM_NAMES = ["enable", "std", "platform", "inconclusive"]
PARAM_VALUES = [ENABLE_OPTS, STD_OPTS, PLATFORM_OPTS, INCONCLUSIVE_OPTS]

# Path to the target
TARGET_DIR = "HPC-Compiler-Fuzzers"

# Change this to "bandit" and adjust command builder
TOOL = "cppcheck"


# ==== COMMAND BUILDERS ====

def build_cppcheck_cmd(params: dict) -> list[str]:
    """Build a cppcheck command for given parameter combination."""
    cmd = [
        "cppcheck",
        f"--enable={params['enable']}",
        f"--std={params['std']}",
        f"--platform={params['platform']}",
        "--inline-suppr",        # example extra flag (optional)
    ]
    if params["inconclusive"]:
        cmd.append("--inconclusive")

    # Target is the unpacked directory from e15.zip
    cmd.append(TARGET_DIR)
    return cmd


# Example Bandit variant:
# def build_bandit_cmd(params: dict) -> list[str]:
#     cmd = [
#         "bandit",
#         "-r",
#         TARGET_DIR,
#         # could encode params into -lll / -ii / -iii, etc.
#     ]
#     return cmd


def build_tool_cmd(params: dict) -> list[str]:
    if TOOL == "cppcheck":
        return build_cppcheck_cmd(params)
    # elif TOOL == "bandit":
    #     return build_bandit_cmd(params)
    else:
        raise ValueError(f"Unknown TOOL: {TOOL}")


# ==== MAIN DRIVER ====

def main() -> None:
    target_path = Path(TARGET_DIR)
    if not target_path.exists():
        raise SystemExit(
            f"Target directory '{TARGET_DIR}' not found. "
            f"Unzip e15.zip so that the sources are in '{TARGET_DIR}/'."
        )

    logs_dir = Path("logs")
    logs_dir.mkdir(exist_ok=True)

    print("PAIRWISE TESTCASES (generated by allpairspy):")
    print("============================================")

    for idx, combo in enumerate(AllPairs(PARAM_VALUES), start=1):
        params = dict(zip(PARAM_NAMES, combo))

        cmd_list = build_tool_cmd(params)
        cmd_str = " ".join(shlex.quote(part) for part in cmd_list)

        print(f"{idx:02}: {cmd_str}")

        # Run tool
        result = subprocess.run(
            cmd_list,
            capture_output=True,
            text=True,
        )

        # Log everything
        log_path = logs_dir / f"testcase_{idx:02}.log"
        with log_path.open("w", encoding="utf-8") as f:
            f.write(f"# Testcase {idx}\n")
            f.write(f"# Parameters: {params}\n")
            f.write(f"# Command: {cmd_str}\n\n")
            f.write("=== STDOUT ===\n")
            f.write(result.stdout)
            f.write("\n=== STDERR ===\n")
            f.write(result.stderr)
            f.write(f"\n=== RETURN CODE: {result.returncode}\n")

    print("\nDone!")
    print("All test runs are logged under ./logs/testcase_XX.log")


if __name__ == "__main__":
    main()
